[tool.poetry]
name = "sdrdm_database"
version = "0.5.0"
description = "An sdRDM-based framework to utilize databases"
authors = ["Jan Range <30547301+JR-1991@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
ibis-framework = { extras = ["mysql"], version = "^8.0.0" }
validators = "^0.22.0"
strawberry-graphql = "^0.209.8"
typer = "^0.9.0"
pydantic = "^2.6.0"
sdrdm = "^0.2"
sqlalchemy = "^2.0.22"
rich = "^13.7.1"
nest-asyncio = "^1.6.0"

[tool.poetry.extras]
mysql = ["pymysql", "sqlalchemy-views", "mysql-connector-python"]
postgres = ["psycopg2", "sqlalchemy-views"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"

[tool.poetry.scripts]
sdrdm-db = "sdrdm_database.cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = ["integration"]
